### ISSUE TITLE
Error on compile assets

### ISSUE THREAD

**Issue by 1giba** [creativetimofficial/vue-material-dashboard#1]
I ran in development mode raised a error. When I built, the dist folder was generated successful.

Error:
![screenshot from 2018-05-16 13-24-00](https://user-images.githubusercontent.com/4941544/40130115-777ff082-590c-11e8-8166-f999f2c1b38a.png)

Build Successful:
![screenshot from 2018-05-16 13-25-46](https://user-images.githubusercontent.com/4941544/40130195-b0febb36-590c-11e8-85cd-82e5d7abfd09.png)

**Comment by dragosct10** [comment]
Hi, @1giba! Thank you for using our product. I noticed that you use an older version of Yarn so please update to the final stable version `1.6.0` and then in your project please go to the `package.json` file and please in the dependencies modify the following lines: `"vue": "2.5.13"` > `"vue": "2.5.16"` and in the devDependencies: `"vue-template-compiler": "2.5.16"` > `"vue-template-compiler": "2.5.16"`. It seems that yarn don't let us open the server without the latest version of vue. After you will do this just type in the console `yarn install` and then `yarn serve` and it should work fine. 

Please let us know if this helps you! 

Regards,
Dragos

**Comment by 1giba** [comment]
Thanks!!
