### ISSUE TITLE
 Preblem with the appearance of the Cards component

### ISSUE THREAD

**Issue by Fejhu** [creativetimofficial/vue-material-dashboard#11]
hi¡ I doing mix this template with laravel but the appearance of the component CARDS is not optimized. look the images, is how if the component cut her up head or part of this.

does you can help me?
![Screenshot_1](https://user-images.githubusercontent.com/44352700/54974581-49d46380-4f73-11e9-8ee1-0c77e713113b.png)
![Screenshot_2](https://user-images.githubusercontent.com/44352700/54974583-49d46380-4f73-11e9-9e53-6c80f8ddde1c.png)

**Comment by dragosct10** [comment]
Hi, @Fejhu! Thank you for using our products. Please, see if the cards have a property like `overflow: hidden`. Like you see in our side everything it's working fine in the product. 

Regards, 
Dragos

**Comment by Fejhu** [comment]
i try change hidden for visible but nothing happen, the card continue with the problem

![Screenshot_4](https://user-images.githubusercontent.com/44352700/55026537-f3ead480-4fe1-11e9-9412-efc005a29f9a.png)

**Comment by ClintOxx** [comment]
I had this issue randomly in the console it said something about a recursive import error with helper.offset

Just rolled back to last commit and it fixed it for now. I was using the vuefiy version but its all the same thibg
