### ISSUE TITLE
Sidebar width not same on mac and windows

### ISSUE THREAD

**Issue by unoiatech** [creativetimofficial/vue-material-dashboard#12]
Hi,
we are facing sidebar  appearance  issue on our website.it take different width on mac and on windows.On window system table data scrolling issue also appear when refresh page then  scroll from bottom to up .
Please find below screenshot : 
1.Window Issue : https://prnt.sc/n3i3ne 
2.Mac Issue :https://prnt.sc/n3hv10

Thanks

**Comment by dragosct10** [comment]
Hi, @unoiatech! Thank you for using our products. Please, give us your link to the project to see what is happening there because we can't reproduce the issue. 

Regards,
Dragos

**Comment by unoiatech** [comment]
Hi,

link to our project :    http://vuedashboard.surge.sh/#/dashboard

there is also issue with scrolling.when we scroll  to the bottom of a  page and open another page the page loads from the bottom not from the top.the page opens from the last scrolled position.please check.

Thanks

**Comment by dragosct10** [comment]
Hi! To fix the problem with the scroll on top please go in src/main.js and put this: 

```js
// configure router
const router = new VueRouter({
  routes, // short for routes: routes
  scrollBehavior: to => {
    if (to.hash) {
      return { selector: to.hash };
    } else {
      return { x: 0, y: 0 };
    }
  },
  linkExactActiveClass: "nav-item active"
});
```

Regard to the problem with the sidebar I can't realise where it's problem, everything looks good on your website. 

Regards, 
Dragos

**Comment by unoiatech** [comment]
Hi Dragos,

the solution you provided for scrolling does not work.The page start from last scrolled position when  we go to new page.
Please look into the sidebar issue also.I am also attaching the screenshot how the sidebar opens on mac.
The sidebar take different widths on windows and mac.The sidebar width is fixed on windows but not on mac.

screenshot: https://prnt.sc/n4kax4

Thanks

**Comment by dragosct10** [comment]
Hi! The solution that I gave it to you it's an official one from the vuejs: https://router.vuejs.org/guide/advanced/scroll-behavior.html and in our side, this works. I will attach you a video to show you that on our MacBooks there are no different widths and we can't reproduce the issue to tell you how to fix it. The video was made on Chrome, but it also works in Safari. 

[sidebar-vue-md-pro.mov.zip](https://github.com/creativetimofficial/vue-material-dashboard/files/3028619/sidebar-vue-md-pro.mov.zip)


Regards, 
Dragos
