### ISSUE TITLE
Any example on how to adapt it to run served by a Flask app?

### ISSUE THREAD

**Issue by lowercase00** [creativetimofficial/vue-material-dashboard#13]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by dragosct10** [comment]
Hi, @lowercase00! Thank you for using our products. Unfortunately, we didn't use the flask app and we can't give you some advice related to this, but maybe someone from our community will see this message and will help you. 

Regards, 
Dragos

**Comment by lowercase00** [comment]
Thanks. I ended up separating my front from my backend making Vue access Flasks' API's. I'll slowly try to implement the dashboard to the front! Thanks
