### ISSUE TITLE
Chart bigger than shown on the demo

### ISSUE THREAD

**Issue by v0idpwn** [creativetimofficial/vue-material-dashboard#14]
# Prerequisites
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
When I run the server, my output is like the demo.

# Current Behavior
When I run the server, the charts in the cards are big. 
![image](https://user-images.githubusercontent.com/14948182/56675667-10d30000-6693-11e9-9ee9-ebe6c774ee0a.png)

## Steps to Reproduce
1. Download from creative tim
2. npm install
3. npm run dev
4. open in the browser

## Context
* Device: PC
* Operating System: both Linux and Windows
* Browser and Version: both Firefox and Chrome

**Comment by dragosct10** [comment]
Hi, @v0idpwn! Thank you for using our products. It's weird because we tested and in our part everything it's working fine and we can't reproduce it. You're sure that you don't add any CSS or something like that?  

Regards, 
Dragos

**Comment by v0idpwn** [comment]
Yes, I just downloaded it. When I tested on another computer (Windows/Chrome), I was still hosting at that Linux PC. Could it be related to the software installed on my computer?

**Comment by v0idpwn** [comment]
Just tried downloading again today and it still happens.

**Comment by dragosct10** [comment]
Hi! It's very weird. You are the first one who said that and we really can't reproduce it. We tried to reproduce but without any luck. Have you tried on another computer? 

Regards, 
Dragos
