### ISSUE TITLE
Issue i cant use material-dashboard.scss inmy project 

### ISSUE THREAD

**Issue by Saedlawi** [creativetimofficial/vue-material-dashboard#15]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes ] I am running the latest version
- [Yes ] I checked the documentation and found no answer
- [ Yse] I checked to make sure that this issue has not already been filed
- [Yes ] I'm reporting the issue to the correct repository (for multi-repository projects)
==================
Dear 

i was bought license for material dashboard pro (developer license) , and i was downlad the app from your site ,  I was copied assets folder from creativtime project folder to my project folder and i changed angular .json to add new style (material-dashboard)  ("src/assets/scss/material-dashboard.scss")"  but the below error  was shown.

can you help me please 
also do you have clear documentation to how i can use material dashboard style in my project thank you

======================================

ERROR in ./src/assets/scss/material-dashboard.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/scss/material-dashboard.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- C:\Users\sabulawi\mainapp4\node_modules\sass-loader\lib\loader.js
- C:\Users\sabulawi\mainapp4\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\sabulawi\mainapp4\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\sabulawi\mainapp4\node_modules\webpack\lib\NormalModule.js
- C:\Users\sabulawi\mainapp4\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\sabulawi\mainapp4\node_modules\webpack\lib\Compiler.js
- C:\Users\sabulawi\mainapp4\node_modules\webpack\lib\webpack.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular-devkit\architect\src\architect-legacy.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular-devkit\architect\src\index.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular\cli\models\architect-command.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular\cli\commands\build-impl.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular\cli\models\command-runner.js
- C:\Users\sabulawi\mainapp4\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\sabulawi\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\sabulawi\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.sassLoader (C:\Users\sabulawi\mainapp4\node_modules\sass-loader\lib\loader.js:46:72)

**Comment by dragosct10** [comment]
Hi, @Saedlawi! Thank you for using our products. Please tell us which product did you use, [Material Dashboard PRO HTML](https://demos.creative-tim.com/material-dashboard-pro/examples/dashboard.html?_ga=2.168235305.941609408.1557126665-2107268403.1556811939), [Vue Material Dashboard PRO](https://demos.creative-tim.com/vue-material-dashboard-pro/?_ga=2.105405579.941609408.1557126665-2107268403.1556811939#/dashboard) or [Material dashboard PRO Angular](https://demos.creative-tim.com/material-dashboard-pro-angular2/dashboard?_ga=2.105405579.941609408.1557126665-2107268403.1556811939)? 

Regards, 
Dragos

**Comment by Saedlawi** [comment]
Thanks for your reply... i am using Material dashboard PRO Angular.

**Comment by dragosct10** [comment]
Hi! This repo's for the vue version. Please open an issue on the angular repo here https://github.com/creativetimofficial/ct-material-dashboard-pro-angular and a colleague will help you. Regards, Dragos
