### ISSUE TITLE
Side-bar icons don't show

### ISSUE THREAD

**Issue by ricar2ce** [creativetimofficial/vue-material-dashboard#17]
when I run the example, the icons in the sidebar and other examples are not shown, I realized that they are the material-icons, when using the md-icon component, some help please
Thanks in advance

**Comment by dragosct10** [comment]
Hi, @ricar2ce! Thank you for using our products. Please show us an example or give us the link to your project, because in our part everything it's working fine. 

Regards, 
Dragos

**Comment by ricar2ce** [comment]
thanks for your attention, I discovered the problem, it was a conflict between my firewall and google material icons, sorry for the inconvenience.
