### ISSUE TITLE
[Bug] Use of Font Awesome Icons

### ISSUE THREAD

**Issue by lgcelarie** [creativetimofficial/vue-material-dashboard#19]
### Version
1.2.1
### Steps to reproduce
Try to use Font Awesome as icons for the app, as per dashboard documentation:
change any icon in the sidebar DashboardLayout.vue to use Font Awesome, i.e:
```
<sidebar-link to="/notifications">
        <md-icon class="fas fa-boxes">notifications</md-icon>
        <p>Notifications</p>
      </sidebar-link>
```

in the same DashboardLayout.vue:
```
export default {
  name: "FontAwesome",
  components: {
    TopNavbar,
    DashboardContent,
    ContentFooter,
    MobileMenu
  }
```
### What is expected?
To see the icons being used as Font Awesome Icons
### What is actually happening?
No icon is shown, nor the font family changed to Font Awesome

---
### Additional comments
No idea if i'm actually setting the name in the right place or doing it right. any help is appreciated

**Comment by dragosct10** [comment]
Hi, @lgcelarie! Thank you for using our products. To use the font awesome please use the `<i class="class="fas fa-boxes""></i>` tag  because the md-icon component it's only for the material icons. 

Regards, 
Dragos
