### ISSUE TITLE
[Bug] Perfect Scrollbar doesn't work

### ISSUE THREAD

**Issue by dacercoolex** [creativetimofficial/vue-material-dashboard#20]
### Version
Vue Material Dashboard Pro - v1.3.1
### Reproduction link
not needed
### Operating System
Linux
### Device
Desktop
### Browser & Version
Chrome 75.0.3770.100 (Build oficial) (64 bits)
### Steps to reproduce
1. Install the demo downloaded from site
2. Run "npm run serve"
### What is expected?
Sidebar scrollbar using perfect scrollbar instead of default browser scrollbar
### What is actually happening?
Is showing the default scrollbar

---

**Comment by dacercoolex** [comment]
![image](https://user-images.githubusercontent.com/32141484/61551692-35d5d580-aa2c-11e9-8650-dec135186314.png)

**Comment by dacercoolex** [comment]
I've done a hack so the Perfect Scrollbar works. 

Turns out that there's a condition in the mounted method of file:

> src/pages/Dashboard/Layout/DashboardLayout.vue

This condition check if the OS is Windows, if it is then the Perfect Scrollbar is activated, if not then it won't. In my case I'm using Linux, that's why it didn't work.

So, to fix it, I've removed the condition so the Perfect Scrollbar gets activated no matter which OS is being used. The code was rewritten as follows:

```
mounted() {
    let docClasses = document.body.classList;
    initScrollbar("sidebar");
    initScrollbar("sidebar-wrapper");
    initScrollbar("main-panel");

    docClasses.add("perfect-scrollbar-on");
  }
```
Please, let me know if there's a better way to it and the reason why the perfect bar is active only in Windows.

Thanks in advance.

**Comment by dragosct10** [comment]
Hi, @dacercoolex! Thank you for using our products and for the solution. We will check if another option it's available, and we will integrate into the next update. 

Regards, 
Dragos
