### ISSUE TITLE
dispaly wrong when use a map package vue-amap,i don't know who's problem

### ISSUE THREAD

**Issue by neighbourwang** [creativetimofficial/vue-material-dashboard#21]
https://github.com/ElemeFE/vue-amap

**Comment by dragosct10** [comment]
Hi, @neighbourwang! Thank you for using our products. Please, show us an example of how this map is rendered?

Regards,
Dragos

**Comment by neighbourwang** [comment]
i just download material dashboard,and replace google map page with gaode map，another javascript  map framwork;the map package for vue link is 'https://github.com/ElemeFE/vue-amap',but the one canvas layer of the map dispaly aways half width of the page;but i use this vue-amap map package in other project have no problem;so i don't kown how to solve this problem,thank you very much!
[vue-material-dashboard-master.zip](https://github.com/creativetimofficial/vue-material-dashboard/files/3466315/vue-material-dashboard-master.zip)

**Comment by dragosct10** [comment]
Hi! Please, can you give us your link to your project to see how can we help you, otherwise we can't figure out? 

Regards, 
Dragos
