### ISSUE TITLE
sir  i want to add sub menu to one of my menu. for example when i click on user profile menu there should open two other submenus. is this possbile if yes how. kinldy guide me i am new to vue.js

### ISSUE THREAD

**Issue by Tehsseen** [creativetimofficial/vue-material-dashboard#22]

**Comment by dragosct10** [comment]
Hi, @Tehsseen! Thank you for using our products. This feature is available in the PRO version. I will close this issue. 

Regards,
Dragos

**Comment by Tehsseen** [comment]
sir i have done 90% of my project will be difficult to develop again in pro. if you could guide me how to add this in current dashboard. thanks.

**Comment by dragosct10** [comment]
Hi, @Tehsseen! Unfortunately, as I told you in the previous message this is a pro feature. We can offer you a discount of 30% OFF for the PRO version of the product and then you will be able to use the sub menu that you want. 

Thank you for your understanding! 

Regards,
Dragos
