### ISSUE TITLE
Material design  styling not working properly

### ISSUE THREAD

**Issue by Tehsseen** [creativetimofficial/vue-material-dashboard#23]
i am using https://vuematerial.io/components/subheader
but i am not getting the proper design. 
some styling classes are not working  and content are  scattered although i have copy paste it from the above mentioned link but in vain. kindly have a look that what could be the problem.

**Comment by dragosct10** [comment]
Hi, @Tehsseen! In the vuematerial framework, we didn't take all the components and translated to our style, so there are some components that are not on our style. Maybe we will implement more components in the next updates. 

Regards, 
Dragos
