### ISSUE TITLE
broken style for md-select, md-accent, and others

### ISSUE THREAD

**Issue by ITEANJD** [creativetimofficial/vue-material-dashboard#3]
for example, md-select with wrong style:
![vue-dashboard1](https://user-images.githubusercontent.com/18269514/42243749-0d2a9b8a-7f1b-11e8-888c-8a28881ddcd3.png)
but it should be like this:
![vue-dashboard2](https://user-images.githubusercontent.com/18269514/42243649-b53c1610-7f1a-11e8-8fff-15f73cc2f454.png)
same goes for md-accent, md-primary, and many other things.
any suggestion to solve this quickly?

**Comment by dragosct10** [comment]
Hi, @ITEANJD! Thank you for using our product. The select style it will be available in the PRO version of the product which will be released soon. Regards, Dragos
