### ISSUE TITLE
Blank screen when using IE 11

### ISSUE THREAD

**Issue by MickaelTH** [creativetimofficial/vue-material-dashboard#7]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [x] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Expecting page to be displayed.

# Current Behavior

Blank screen.

# Failure Information (for bugs)

This may be related to IE 11 not supporting promise. Maybe adding a poly fill can resolve the issue?

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open IE 11
2. Go to https://demos.creative-tim.com/vue-material-dashboard/#/dashboard
3. Blank page

## Context

* Device: Desktop
* Operating System: Win 10
* Browser and Version: IE 11

## Failure Logs

No error or logs found.

![2018-11-02 003319](https://user-images.githubusercontent.com/26375917/47898854-37656a80-deaa-11e8-867c-569b9746e83e.png)

**Comment by dragosct10** [comment]
Hi, @MickaelTH! Thank you for using our products. The product's not supported on IE11 because vuematerial.io framework does not support the IE so, when they will have support on IE it will work. Also on our readme from this repo if you see on the supported browsers IE it's not included. Regards, Dragos

**Comment by MickaelTH** [comment]
Hi,

Thank you for the reply, I understand this is not related directly to the theme and yes there is no IE logo on the readme. Would be also good to add it on the download page (https://www.creative-tim.com/product/vue-material-dashboard).

Anyway we still have lot of people using IE on our end (enterprise) so will have to check other of you theme.
