### ISSUE TITLE
[Bug] Npm run build results in blank page

### ISSUE THREAD

**Issue by marmz** [creativetimofficial/vue-material-dashboard#77]
### Version
1.5.0
### Reproduction link
https://github.com/marmz/csb-4bzy9t
### Operating System
Linux Mint
### Device
Laptop HP
### Browser & Version
Chrome 96.0.4664.110 64 bit
### Steps to reproduce
npm run build
### What is expected?
Production version of given website
### What is actually happening?
Blank page with some js and css included

---
### Additional comments
Linked github page with build results.

**Comment by sajadevo** [comment]
Hey there,

We've updated the product and now it'w working fine just update to the latest version of the product.

Cheers,
Sajad
