### ISSUE TITLE
Error in render: "TypeError: Cannot read property 'options' of undefined"

### ISSUE THREAD

**Issue by hosein2398** [creativetimofficial/vue-material-dashboard#9]
I'm using latest version and after running `dev` command i face this:
![image](https://user-images.githubusercontent.com/17067774/48982287-b0e12900-f0f5-11e8-9b41-497d6e3c36ff.png)
And sidemenu options do not appear at all.

**Comment by dragosct10** [comment]
Hi, @hosein2398! Thank you for using our products. We test it and on our side everything it's working fine. You are on windows? You are sure that you have the latest version of node.js? 

Regards,
Dragos

**Comment by mlq** [comment]
I can confirm the issue with version ``3.0.2`` of ``vue-router``. Downgrading to ``3.0.1`` works.

**Comment by dragosct10** [comment]
Hi! Please take the latest version. We fixed this. 

Regards, 
Dragos

**Comment by hosein2398** [comment]
Thanks for your support, it's fixed now.
There is only one problem:
![image](https://user-images.githubusercontent.com/17067774/49024650-38d73980-f1af-11e8-9d71-ed1da95ee95a.png)
It's fiexed by installing `eslint-loader`

**Comment by AnkBurov** [comment]
Do javascripters know how to write tests?
